import * as path from "path";
import * as fs from "fs/promises";
import type { Tool, ToolExecutionContext, ToolResult } from "./types";
import { resolveInWorkspace } from "../utils/workspace-path";

const DOC_TYPES = [
  "architecture",
  "api-reference",
  "decision-record",
  "component-spec",
  "technical",
] as const;

export const generateDocTool: Tool = {
  name: "generate_doc",
  description:
    "Write a technical document to a Markdown file. Provide the full Markdown content. Supported docTypes: architecture, api-reference, decision-record, component-spec, technical. A metadata comment is prepended automatically.",
  requiresApproval: true,
  parameters: {
    type: "object",
    properties: {
      filename: {
        type: "string",
        description:
          "Output file path relative to workspace root, e.g. docs/ARCHITECTURE.md",
      },
      docType: {
        type: "string",
        enum: [...DOC_TYPES],
        description: "Document type — appended as metadata in the file header",
      },
      content: {
        type: "string",
        description: "Full Markdown content of the document",
      },
    },
    required: ["filename", "docType", "content"],
  },

  async execute(
    args: Record<string, unknown>,
    ctx: ToolExecutionContext,
  ): Promise<ToolResult> {
    const { filename, docType, content } = args as {
      filename: string;
      docType: string;
      content: string;
    };

    if (!ctx.workspaceRoot || ctx.workspaceRoot.trim() === "") {
      return {
        success: false,
        output:
          "No workspace folder is open. Open a folder in VS Code first before generating documents.",
      };
    }

    const fullPath = resolveInWorkspace(ctx.workspaceRoot, filename);
    if (!fullPath) {
      return {
        success: false,
        output: `Path "${filename}" is outside the workspace — not allowed.`,
      };
    }

    await fs.mkdir(path.dirname(fullPath), { recursive: true });

    const date = new Date().toISOString().slice(0, 10);
    const header = `<!-- generated by Champ | type: ${docType} | date: ${date} -->\n\n`;
    await fs.writeFile(fullPath, header + content, "utf-8");

    // Verify the file was actually written before claiming success.
    try {
      await fs.access(fullPath);
    } catch {
      return {
        success: false,
        output: `generate_doc: file write appeared to succeed but ${filename} is not readable. Check disk space and permissions.`,
      };
    }

    ctx.reportProgress(`Document written to ${filename}`);
    return {
      success: true,
      output: `Document written to ${filename}`,
      metadata: { filesCreated: [fullPath] },
    };
  },
};
